dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2"
dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.8.2"
networks:
  goerli:
    publish_source: True
  mainnet-fork:
    publish_source: False
